### ISSUE TITLE
exec error

### ISSUE THREAD

**Issue by bufsnake** [jakespringer/angr_ctf#9]
```bash
(angr) angr@fed003dbb7b2:~/angr_ctf/solutions/07_angr_symbolic_file$ python solve07.py 07_angr_symbolic_file
Traceback (most recent call last):
  File "solve07.py", line 130, in <module>
    main(sys.argv)
  File "solve07.py", line 91, in main
    password_file = angr.storage.SimFile(filename, file_options, content=symbolic_file_backing_memory, size=symbolic_file_size_bytes)
TypeError: __init__() got multiple values for argument 'content'
```

**Comment by xiaoshipricne** [comment]
me too...
